# Change these first
owner: needbrainz # Your GitHub organization or username, where this repository lives
repo: websites-upptime # The name of this repository
sites:
  - name: needbrainz.com
    url: https://needbrainz.com
  - name: magnetiseur-reiki.ch
    url: https://www.magnetiseur-reiki.ch
  - name: physio-vd.ch
    url: https://www.physio-vd.ch
  - name: acu-vd.ch
    url: https://www.acu-vd.ch
  - name: plausible
    url: https://plausible.needbrainz.com
assignees:
  - yhaefliger
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.needbrainz.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: NB-Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
